### ISSUE TITLE
text-xs produces invalid clamp

### ISSUE THREAD

**Issue by alban-ameti** [davidhellmann/tailwindcss-fluid-type#26] opened 2023-08-11 03:43 UTC
Hi,

First of thanks for the package it is really useful.

I have noticed that the default 'xs' property produces the following:

font-size: clamp(0.8888888888888888rem, calc(0.8888888888888888rem + ((0.8680555555555557 - 0.8888888888888888) * ((100vw - 20rem) / (96 - 20)))), 0.8680555555555557rem);

The min value is higher then the max value.

**Comment by davidhellmann** [comment] 2023-08-11 06:49
Thanks for reporting! I will look into that the next days. Can you share your config please? Would be great.

**Comment by salmans-teikametrics** [comment] 2023-08-16 14:36
I am also facing the same issue, here is my config

```
    fluidTypePlugin({
      // your fluid type settings
      // works only with unitless numbers
      // This numbers are the defaults settings
      settings: {
        fontSizeMin: 1.25, // 1.25rem === 20px
        fontSizeMax: 0.875, // 0.875rem === 14px
        ratioMin: 1.125, // Multiplicator Min
        ratioMax: 1.2, // Multiplicator Max
        screenMin: 20, // 20rem === 320px
        screenMax: 96, // 96rem === 1536px
        unit: 'rem', // default is rem but it's also possible to use 'px'
        prefix: '', // set a prefix to use it alongside the default font sizes
        extendValues: false // When you set extendValues to true it will extend the default values. Set it to false to overwrite the values.
      },
      // Creates the text-xx classes
      // This are the default settings and analog to the tailwindcss defaults
      // Each `lineHeight` is set unitless and we think that's the way to go especially in context with fluid type.
      values: {
        xs: [-2, 1.6],
        sm: [-1, 1.6],
        base: [0, 1.6],
        lg: [1, 1.6],
        xl: [2, 1.2],
        '2xl': [3, 1.2],
        '3xl': [4, 1.2],
        '4xl': [5, 1.1],
        '5xl': [6, 1.1],
        '6xl': [7, 1.1],
        '7xl': [8, 1],
        '8xl': [9, 1],
        '9xl': [10, 1]
      }
    })
```

**Comment by salmans-teikametrics** [comment] 2023-08-16 14:57
@davidhellmann Here is the fix. I do not have permission to create a PR

```
const defaults = require("../config/defaults");

module.exports = (value, data) => {
    if (data.settingsAreNumbers && data.settings) {
        const sFtMin = data.settings?.fontSizeMin
        const sFtMax = data.settings?.fontSizeMax
        const sFtRMin = data.settings?.ratioMin
        const sFtRMax = data.settings?.ratioMax
        const sFtSMin = data.settings?.screenMin
        const sFtSMax = data.settings?.screenMax
        const unit = data.unit
        const sFtUnit = typeof unit === 'string' ? unit : 'rem';
        const minValue = sFtMin * Math.pow(sFtRMin, value);
        const maxValue = sFtMax * Math.pow(sFtRMax, value);
        const ftMin = Math.min(minValue, maxValue);
        const ftMax = Math.max(minValue, maxValue);
        return `clamp(${ftMin}${sFtUnit}, calc(${ftMin}${sFtUnit} + ((${ftMax} - ${ftMin}) * ((100vw - ${sFtSMin}${sFtUnit}) / (${sFtSMax} - ${sFtSMin})))), ${ftMax}${sFtUnit})`;
    }
    return value;
}
```

**Comment by davidhellmann** [comment] 2023-08-16 15:02
Thanks! Still busy, but I'll try to check that tomorrow.
But @salmans-teikametrics when you fork it it's also not possible to create a PR?

**Comment by salmans-teikametrics** [comment] 2023-08-16 15:12
I created a PR from the fork

https://github.com/davidhellmann/tailwindcss-fluid-type/pull/27

**Comment by salmans-teikametrics** [comment] 2023-08-16 18:22
I did some testing, but it is not behaving the way it should be, With the given config for the smaller viewport, it should produce the bigger font size and for bigger it needs to be smaller. 
Readjusting the MIN and MAX values is correct, but I guess the formula for PREFERRED_VALUE (second parameter to clamp) needs to be updated.

**Comment by davidhellmann** [comment] 2023-08-16 18:46
Thanks for the update. I'll have a look tomorrow.

**Comment by davidhellmann** [comment] 2023-08-17 05:42
I played around with that, and it's a bit of intended behavior. I know it's maybe not 100% what you guys expected. The negative values should not be used that much, and with the current approach, the layout is more robust because it's forced to use the bigger font size values from the two scales. 

But I'm open for discussion here and maybe it needs a bit more test cases. Most of the time the config is in this way: smaller sizes on smaller screens and bigger sizes on bigger screens.

**Comment by alban-ameti** [comment] 2023-08-21 12:07
I have reported this just for the sake of it being correct in the syntax.
I expected to see the first value in clamp to always be the min and the last to always be the max.
If in fact this is how it is expected to behave I am happy for it to stay as is.

**Comment by davidhellmann** [comment] 2023-08-22 11:46
I think technically it's not 100% correct, but from a logical point of view I think it's fine. I'll close the issue for now but that means not that I don't think about it further. :)

**Comment by salmans-teikametrics** [comment] 2023-08-22 15:50
@davidhellmann that [PR](https://github.com/davidhellmann/tailwindcss-fluid-type/pull/27) is still valid, as a `clamp` won't allow `MIN > MAX`. This will always pick the max size and ignore the stretch fit size (Preferred value). 

https://drafts.csswg.org/css-sizing/#fit-content-block-size

https://developer.mozilla.org/en-US/docs/Web/CSS/clamp

**Comment by davidhellmann** [comment] 2023-08-22 15:52
OK, will have a look later this week. Thanks for the update.

**Comment by davidhellmann** [comment] 2024-03-25 20:12
Published that yesterday.

**Closed by davidhellmann** 2024-03-25 20:12 UTC
